name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.3.2'

      - name: Install project
        run: make install
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make test

      - name: Publish package on PyPi
        run: |
          poetry config http-basic.pypi __token__ ${{secrets.PYPI_TOKEN}}
          poetry build
          poetry publish

      - name: Parse changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref_name }}

      - name: Publish GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ steps.changelog.outputs.version }}
          body: |
            ## ${{ steps.changelog.outputs.version }} - ${{ steps.changelog.outputs.date }}

            ${{ steps.changelog.outputs.changes }}
          draft: true
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
